// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdQjBZjdqPXNZslFhF0JmVSlVQk_yJJuM',
    appId: '1:879540621070:android:fc13270840f5392f4f515f',
    messagingSenderId: '879540621070',
    projectId: 'flutter-food-delivary-app',
    storageBucket: 'flutter-food-delivary-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeCDDd9OvoDze8hbzuKnVYotd8_HabDbw',
    appId: '1:879540621070:ios:f2aecbcccd42863a4f515f',
    messagingSenderId: '879540621070',
    projectId: 'flutter-food-delivary-app',
    storageBucket: 'flutter-food-delivary-app.appspot.com',
    androidClientId: '879540621070-r3qm0dkne5mmtb235pfv709ecg4g0gf0.apps.googleusercontent.com',
    iosClientId: '879540621070-il0aiilk2lmeidsf2dnc3daq011mc0ab.apps.googleusercontent.com',
    iosBundleId: 'com.gameonanil.fooddeliveryapp',
  );
}
